// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ADO_DENTAL_CLINIC.Models
{
    public partial class CityNameResult
    {
        public string CITY { get; set; }
    }
}
