// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADO_DENTAL_CLINIC.Models;

public partial class DentalClinic
{
    public int Id { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public int DentistId { get; set; }

    public int LicenseId { get; set; }

    public virtual Dentist Dentist { get; set; }

    public virtual License License { get; set; }
}