// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ADO_DENTAL_CLINIC.Models;

public partial class Dentist
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public int CategoryId { get; set; }

    public int SpecialityId { get; set; }

    public DateOnly? BeginDate { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<DentalClinic> DentalClinics { get; set; } = new List<DentalClinic>();

    public virtual Speciality Speciality { get; set; }
}