// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ADO_DENTAL_CLINIC.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ADO_DENTAL_CLINIC.Models
{
    public partial interface IDENTAL_ContextProcedures
    {
        Task<List<CityNameResult>> CityNameAsync(string reg, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RegionNameResult>> RegionNameAsync(string reg, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
